2023-01-30 14:51:32,879 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-01-30 14:51:32,879 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Lenovo\marketautomation\venv\Lib\site-packages\instabot\bot\bot.py
2023-01-30 14:51:32,879 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-01-30 14:51:33,379 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2023-01-30 14:51:33,797 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2023-01-30 14:51:34,188 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2023-01-30 14:51:34,520 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2023-01-30 14:51:38,754 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2023-01-30 14:51:38,756 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXEZBYP-CoGwht_rdWCCZ-Wys_6l4zRgBZNiYIyeuMEzd0NHJ2llHk7Lj6SHzmHVvNHD3Ss/AfxkKuBeS1eSVi1STfg0VoJjKuCjx6i6WT-Hb9Xn-h6HJgePfCS0edpcm27N7Nwmx7pcjJAPd5ZfQQ/","api_path":"/challenge/AXEZBYP-CoGwht_rdWCCZ-Wys_6l4zRgBZNiYIyeuMEzd0NHJ2llHk7Lj6SHzmHVvNHD3Ss/AfxkKuBeS1eSVi1STfg0VoJjKuCjx6i6WT-Hb9Xn-h6HJgePfCS0edpcm27N7Nwmx7pcjJAPd5ZfQQ/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2023-01-30 14:51:38,756 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2023-01-30 14:51:38,757 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2023-01-30 14:51:38,760 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2023-01-30 14:52:31,207 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-01-30 14:52:31,226 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Lenovo\marketautomation\venv\Lib\site-packages\instabot\bot\bot.py
2023-01-30 14:52:31,227 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-01-30 14:52:31,633 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2023-01-30 14:52:31,635 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-01-30 14:52:31,636 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-01-30 14:52:31,637 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
